audit:
  checklist:
    url: http://localhost:9100/
complete:
  fail: Process Completed - Failure
  success: Process Completed - Success
conctact:
  name: Audit Management System
contact:
  email: ams@gmail.com
  web: ams.com
feign:
  exp: Feign  Exception Caught
  'null': Feign Proxy returned Null Object
  proxy:
    exp: Feign Proxy Exception Caught
field:
   exp: Some Fields are missing! Please Check...
fos:
  auditbenchmark: http://localhost:9300/
  auth: http://localhost:9400/
logging:
  level:
    org:
      hibernate:
        stat: debug
project:
  auditType: Internal
  status:
    green: GREEN
    red: RED
remedial:
  action:
    'no': No action needed
    'yes':
      one: Action to be taken in 2 weeks
server:
  port: 9200

spring:
  application:
    name: auditSeverity
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:Audit
    username: audit
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
string:
  end: End
  invalid:
    cred: Invalid Credentials
  main:
    package: com.cts.AuditSeverity
  'null':
    exception: Array out of bounds
  req: 'Request{}:'
  start: Start
  swagg:
    desc: Audit Severity Service return the remedial action and project execution
      status of Internal audit type responses selected by user
    help: Help
    lic: Audit 1.0
    title: Audit Severity Service Documentation
    ver: 1.0
  token:
    exp: Token Expired! login again
  valfail: Validation Failed
valcheck:
  fail: End checkTokenValidity fail
  success: End checkTokenValidity success

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

