version: 0.2

phases:
  install:
    runtime-versions: 
      java: openjdk11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - IMAGE_URI=${REPOSITORY_URI}:LATEST
  build:
    commands:
      - echo Build started on `date`
      - echo building java
      - cd Documents
      - cd "AUDIT CLOUD"
      - cd AuditAuthentication
      - mvn clean package -Ddockerfile.skip
      - echo Building the Docker image...
      - docker build --tag $IMAGE_URI .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $IMAGE_URI
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > imagedefinitions.json
artifacts:
    files: 
      - imagedefinitions.json