version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
      java: corretto11
  pre_build:
    commands:
        - echo Logging in to Amazon ECR...
        - aws --version
        - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 565108160771.dkr.ecr.us-east-1.amazonaws.com
        - REPOSITORY_URI=565108160771.dkr.ecr.us-east-1.amazonaws.com/audit-authentication
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn -f Documents/"AUDIT CLOUD"/AuditAuthentication/pom.xml clean install -DskipTests=true
      - echo Building the docker image
      - docker build -f Documents/"AUDIT CLOUD"/AuditAuthentication/Dockerfile -t audit-authentication .
      - docker tag audit-authentication 565108160771.dkr.ecr.us-east-1.amazonaws.com/audit-authentication:audit-authentication
  post_build:
    commands:
        - echo Build completed on `date`
        - echo Pushing the Docker images...
        - docker push 565108160771.dkr.ecr.us-east-1.amazonaws.com/audit-authentication:audit-authentication
        - echo Writing image definitions file...
        - printf '[{"name":"audit-authentication","imageUri":"%s"}]' 565108160771.dkr.ecr.us-east-1.amazonaws.com/audit-authentication:audit-authentication > imagedefinitions.json

artifacts:
  files: Documents/AUDIT CLOUD/AuditAuthentication/imagedefinitions.json